version: "3.7"
services:
  web:
    build: dockers/webapp-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    working_dir: /src
    entrypoint: bin/rails server
  dev:
    build: dockers/webapp-dev
    volumes:
      - .:/src
    working_dir: /src
    entrypoint: /bin/bash
  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
volumes:
  dbdata:
