version: "3.7"
services:
  # web:
  #   build: dockers/webapp-dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/src
  #   working_dir: /src
  #   command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  dev:
    build: dockers/webapp-dev
    volumes:
      - .:/src
    working_dir: /src
    entrypoint: /bin/bash
    ports:
      - "3000:3000"
  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
volumes:
  dbdata:
